<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>6b53b027-76c0-4cf7-b55a-c17f2031c2ba</UserSecretsId>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<SatelliteResourceLanguages>zh-TW</SatelliteResourceLanguages>
	<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\**" />
    <Compile Remove="_data\**" />
    <Compile Remove="_log\**" />
    <Compile Remove="_md\**" />
    <Compile Remove="_srcOut\**" />
    <Compile Remove="_upload\**" />
    <Content Remove="_data\**" />
    <Content Remove="_md\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <EmbeddedResource Remove="_data\**" />
    <EmbeddedResource Remove="_log\**" />
    <EmbeddedResource Remove="_md\**" />
    <EmbeddedResource Remove="_srcOut\**" />
    <EmbeddedResource Remove="_upload\**" />
    <None Remove="wwwroot\**" />
    <None Remove="_data\**" />
    <None Remove="_log\**" />
    <None Remove="_md\**" />
    <None Remove="_srcOut\**" />
    <None Remove="_upload\**" />
  </ItemGroup>

  <ItemGroup>
	<Content Include="_template\**" CopyToPublishDirectory="PreserveNewest" />
	<Compile Remove="Controllers\UiController.cs" />
	<Content Include="key.txt" />
    <Content Include="_image\noImage.jpg">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.10" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Base\BaseApi\BaseApi.csproj" />
    <ProjectReference Include="..\Base\BaseWeb\BaseWeb.csproj" />
    <ProjectReference Include="..\Base\Base\Base.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
