export default class InputTypeEstr {
    static readonly Check = "check";
    static readonly Date = "date";
    static readonly DateTime = "dt";
    static readonly Decimal = "dec";
    static readonly File = "file";
    static readonly Hide = "hide";
    static readonly Html = "html";
    static readonly Integer = "int";
    static readonly Link = "link";
    static readonly Modal = "modal";
    static readonly Password = "pwd";
    static readonly Radio = "radio";
    static readonly Read = "read";
    static readonly Select = "select";
    static readonly Sort = "sort";
    static readonly Text = "text";
    static readonly Textarea = "textarea";
}
