import EditModeEstr from "./enum/EditModeEstr";
import FunEstr from "./enum/FunEstr";
import InputTypeEstr from "./enum/InputTypeEstr";
import MouseEstr from "./enum/MouseEstr";
import NodeTypeEstr from "./enum/NodeTypeEstr";

import AjaxDto from "./dto/AjaxDto";
import BaseResDto from "./dto/BaseResDto";
import ChartDto from "./dto/ChartDto";
import EditDto from "./dto/EditDto";
import ErrorRowDto from "./dto/ErrorRowDto";
import IdStrDto from "./dto/IdStrDto";
import IdStrExtDto from "./dto/IdStrExtDto";
import ResultDto from "./dto/ResultDto";

import _Ajax from "./svc/_Ajax";
import _Array from "./svc/_Array";
import _Assert from "./svc/_Assert";
import _Browser from "./svc/_Browser";
import _Btn from "./svc/_Btn";
import _Chart from "./svc/_Chart";
import _Code from "./svc/_Code";
import _Date from "./svc/_Date";
import _Dom from "./svc/_Dom";
import _Edit from "./svc/_Edit";
import _Error from "./svc/_Error";
import _File from "./svc/_File";
import _Flow from "./svc/_Flow";
import _Form from "./svc/_Form";
import _Fun from "./svc/_Fun";
import _Group from "./svc/_Group";
import _Helper from "./svc/_Helper";
import _Html from "./svc/_Html";
import _iBase from "./svc/_iBase";
import _iCheck from "./svc/_iCheck";
import _iColor from "./svc/_iColor";
import _iDate from "./svc/_iDate";
import _iDt from "./svc/_iDt";
import _iFile from "./svc/_iFile";
import _iHtml from "./svc/_iHtml";
import _iLink from "./svc/_iLink";
import _Input from "./svc/_Input";
import _iNum from "./svc/_iNum";
import _iRadio from "./svc/_iRadio";
import _iRead from "./svc/_iRead";
import _iSelect from "./svc/_iSelect";
import _iText from "./svc/_iText";
import _iTextarea from "./svc/_iTextarea";
import _Json from "./svc/_Json";
import _Jwt from "./svc/_Jwt";
import _Leftmenu from "./svc/_Leftmenu";
import _Log from "./svc/_Log";
import _Modal from "./svc/_Modal";
import _Nav from "./svc/_Nav";
import _Num from "./svc/_Num";
import _Obj from "./svc/_Obj";
import _Pjax from "./svc/_Pjax";
import _Prog from "./svc/_Prog";
import _Qrcode from "./svc/_Qrcode";
import _Str from "./svc/_Str";
import _Switch from "./svc/_Switch";
import _Tab from "./svc/_Tab";
import _Table from "./svc/_Table";
import _Temp from "./svc/_Temp";
import _Time from "./svc/_Time";
import _Tool from "./svc/_Tool";
import _Valid from "./svc/_Valid";
import _Var from "./svc/_Var";

import CrudE from "./svc/CrudE";
import CrudR from "./svc/CrudR";
import Datatable from "./svc/Datatable";
import EditMany from "./svc/EditMany";
import EditOne from "./svc/EditOne";
import FlowLine from "./svc/FlowLine";
import FlowMany from "./svc/FlowMany";
import FlowNode from "./svc/FlowNode";
import FlowView from "./svc/FlowView";
import Page from "./svc/Page";

const win = window as any;
win.EditModeEstr = EditModeEstr;
win.FunEstr = FunEstr;
win.InputTypeEstr = InputTypeEstr;
win.MouseEstr = MouseEstr;
win.NodeTypeEstr = NodeTypeEstr;

win.AjaxDto = AjaxDto;
win.BaseResDto = BaseResDto;
win.ChartDto = ChartDto;
win.EditDto = EditDto;
win.ErrorRowDto = ErrorRowDto;
win.IdStrDto = IdStrDto;
win.IdStrExtDto = IdStrExtDto;
win.ResultDto = ResultDto;

win._Ajax = _Ajax;
win._Array = _Array;
win._Assert = _Assert;
win._Browser = _Browser;
win._Btn = _Btn;
win._Chart = _Chart;
win._Code = _Code;
win._Date = _Date;
win._Dom = _Dom;
win._Edit = _Edit;
win._Error = _Error;
win._File = _File;
win._Flow = _Flow;
win._Form = _Form;
win._Fun = _Fun;
win._Group = _Group;
win._Helper = _Helper;
win._Html = _Html;
win._iBase = _iBase;
win._iCheck = _iCheck;
win._iColor = _iColor;
win._iDate = _iDate;
win._iDt = _iDt;
win._iFile = _iFile;
win._iHtml = _iHtml;
win._iLink = _iLink;
win._Input = _Input;
win._iNum = _iNum;
win._iRadio = _iRadio;
win._iRead = _iRead;
win._iSelect = _iSelect;
win._iText = _iText;
win._iTextarea = _iTextarea;
win._Json = _Json;
win._Jwt = _Jwt;
win._Leftmenu = _Leftmenu;
win._Log = _Log;
win._Modal = _Modal;
win._Nav = _Nav;
win._Num = _Num;
win._Obj = _Obj;
win._Pjax = _Pjax;
win._Prog = _Prog;
win._Qrcode = _Qrcode;
win._Str = _Str;
win._Switch = _Switch;
win._Tab = _Tab;
win._Table = _Table;
win._Temp = _Temp;
win._Time = _Time;
win._Tool = _Tool;
win._Valid = _Valid;
win._Var = _Var;
win.CrudE = CrudE;
win.CrudR = CrudR;
win.Datatable = Datatable;
win.EditMany = EditMany;
win.EditOne = EditOne;
win.FlowLine = FlowLine;
win.FlowMany = FlowMany;
win.FlowNode = FlowNode;
win.FlowView = FlowView;
win.Page = Page;