USE [master]
GO

/****** Object:  Database [Db]    Script Date: 2019/8/4 ¤U¤È 04:39:11 ******/
CREATE DATABASE [Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Db.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Db_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Db] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Db] SET ARITHABORT OFF 
GO

ALTER DATABASE [Db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Db] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Db] SET  MULTI_USER 
GO

ALTER DATABASE [Db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Db] SET  READ_WRITE 
GO


