import EditOne from './EditOne';
import EditMany from './EditMany';
export default class CrudE {
    private _nowFun;
    private _Edits;
    private _multiEdit;
    private _nowEditNo;
    private _Edit0;
    constructor(edits: any);
    getEditByNo(editNo: number): EditOne | EditMany;
    viewFileByEditNo(editNo: number, table: string, fid: string): void;
    setGlobal(): void;
    private _initEdit0;
    private _initForm;
    mEditGetDivEdit(): any;
    mEditSetEditNo(editNo: number): void;
    mEditGetEditNo(): number;
    loadJson(json: any): void;
    private _loadJson2;
    afterOpen(fun: string, json: any): void;
    setEditStatus(fun: string): void;
    private _hasFile;
    private _getUpdJson;
    private _getUpdJson2;
    validAll(): boolean;
    afterSave(data: any): void;
    private _afterSaveDraft;
    private _resetForm;
    isEditMode(): boolean;
    private _getJsonAndEditA;
    loadJsonAndEdit(json: any, fun: string): void;
    private _EditGetChild;
    private _EditGetChildLen;
    editToNew(): void;
    dataSetFileJson(data: any, fileJson: any): void;
    onCreate(): void;
    onUpdateA(key: any): Promise<boolean>;
    onViewA(key: any): Promise<boolean>;
    onSignA(key: any): Promise<boolean>;
    onCopyA(key: any): Promise<void>;
    onOpenModal(title: string, fid: string, required: boolean, maxLen: number): void;
    onSaveA(): Promise<void>;
    onDraftA(): Promise<void>;
}
