export default class EditMany {
    private mode;
    private modeData;
    private systemError;
    private kid;
    private rowFilter;
    private sortFid;
    private hasRowTpl;
    private hasRowFilter;
    private rowTpl;
    private hasEform;
    private rowsBox;
    private eform;
    private deletedRows;
    private newIndex;
    private validator;
    private fnReset;
    private fnLoadRows;
    private fnValid;
    private fnGetUpdJson;
    _childs: EditMany[];
    fidTypes: string[];
    fidTypeLen: number;
    fidRadios: string[];
    hasFile: boolean;
    fileLen: number;
    fileFids: string[];
    constructor(kid: string, rowsBoxId?: string, rowTplId?: string, rowFilter?: string, sortFid?: string);
    showErrors(rows: any[] | null): void;
    setChilds(childs: EditMany[]): void;
    initUrm(fids: string[]): void;
    private _isNewBox;
    reset(rowsBox?: JQuery, forNew?: boolean): void;
    private _resetVar;
    private _resetDeletes;
    private _urmLoadRows;
    private _urmGetUpdJson;
    private _urmReset;
    loadRowsBySys(rows: any[]): void;
    loadRowByBox(rowBox: JQuery, row: any, index: number): void;
    loadRowsByRsb(rows: any[] | null, reset?: boolean, rowsBox?: JQuery): void;
    valid(): boolean;
    getKey(rowBox: JQuery): string;
    private _checkRowFilter;
    private _checkRowTpl;
    private _elmToRowBox;
    idToRowBox(id: string): JQuery;
    getUpdJsonBySys(upKey: string): any;
    getUpdJsonByRsb(upKey: string, rowsBox?: JQuery): any;
    getUpdRow(box: JQuery): any;
    getUpdRows(upKey: string, rowsBox?: JQuery): any[] | null;
    getDeletes(): string | null;
    onAddRow(): void;
    addRow(row?: any, rowsBox?: JQuery, newId?: number): any;
    onDeleteRow(): void;
    deleteRow(key: string, rowBox?: JQuery): void;
    deleteAll(): void;
    onViewFile(table: string, fid: string): Promise<void>;
    private _renderRow;
    dataAddFiles(levelStr: string, data: FormData, rowsBox?: JQuery): any;
    rowSetFkey(row: any, fkey: string): void;
    rowsSetFkey(rows: any[] | null, fkey: string): void;
    rowsToNew(): void;
    setNewIndex(index: number): void;
    setNewIdByBox(box: JQuery, newId?: number): number;
    setSort(rowsBox?: JQuery): void;
    private _getRowsBox;
}
