export default class FlowMany {
    private OrSep;
    private AndSep;
    private ColSep;
    private FtMenu;
    private FtStartNode;
    private InitLineCfg;
    private isEdit;
    private mNode;
    private mLine;
    private divLinesBox;
    private eformNodes;
    private eformLines;
    private modalNodeProp;
    private modalLineProp;
    private eformNodeProp;
    private tbodyLineCond;
    private tplNode;
    private tplLine;
    private tplLineCond;
    private nowIsNode;
    private nowFlowItem;
    private condOpExprs;
    private condOpShows;
    private flowView;
    constructor(areaId: string, mNode: any, mLine: any);
    private fnMoveNode;
    private fnAfterAddLine;
    fnShowMenu(event: any, isNode: boolean, flowItem: any): void;
    reset(): void;
    setEdit(status: boolean): void;
    private _setFlowEvent;
    loadNodes(rows: any): void;
    loadLines(rows: any): void;
    addNode(nodeType: string, name?: string): void;
    deleteNode(node: any): void;
    deleteLine(line: any): void;
    private _condStrToLabel;
    private _condStrToList;
    private _getCondStr;
    showNodeProp(node: any): void;
    showLineProp(line: any): void;
    onAddNode(nodeType: string): void;
    private _menuStatus;
    onMenuEdit(): void;
    onMenuDelete(): void;
    onMenuView(): void;
    onAddLineCond(): void;
    onDeleteLineCond(btn: Elm): void;
    onModalNodeOk(): void;
    onModalLineOk(): void;
}
